export const products = [
    {
        id: "1",
        marca: "Adidas",
        title: "Zapatillas adidas Grand Court Alpha",
        price: 129.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "ZAPATILLAS VERSÁTILES CON EL INCONFUNDIBLE ADN DE ADIDAS",
        description: "Diseño clásico con un toque moderno, las adidas Grand Court Alpha son la combinación perfecta de estilo y funcionalidad. Estas zapatillas, elegantes y deportivas, se adaptan fácilmente a cualquier look, asegurando comodidad durante todo el día.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027967/Proyecto-Reacts/Zapatillas/wyebrdjcmjluvwcj5srs.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027970/Proyecto-Reacts/Zapatillas/whycijog0bhd3lmloi1u.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027968/Proyecto-Reacts/Zapatillas/unkk14zkqajvc5g1nkgz.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027970/Proyecto-Reacts/Zapatillas/pdxdthel0jq5hytqnuxn.webp",
        
    },
    {
        id: "2",
        marca:"Adidas",
        title: "Zapatillas adidas X_ Plrboost",
        price: 195.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "ZAPATOS PARA LOOKS DIARIOS, FABRICADOS EN PARTE CON MATERIALES RECICLADOS.",
        description: "El estilo para moverse por la ciudad; la comodidad para aplastar tu ajetreo diario. Estos zapatos adidas reúnen todo lo que necesitas en un estilo elegante inspirado en el running. La entresuela BOOST hace que cada paso se sienta sin esfuerzo. La parte superior de malla brinda soporte transpirable. Fabricada con una serie de materiales reciclados, esta parte superior presenta al menos un 50 % de contenido reciclado.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027971/Proyecto-Reacts/Zapatillas/aglpcbholaue59xuovbo.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027949/Proyecto-Reacts/Zapatillas/ygmplumienbdbfafksgs.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027950/Proyecto-Reacts/Zapatillas/o5muibond4m98icjl8ys.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027954/Proyecto-Reacts/Zapatillas/gghhhxskguw6zmuppb1u.webp",
    },
    {
        id: "3",
        marca:"Adidas",
        title: "Zapatillas adidas VL Court 3.0",
        price: 129.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "ZAPATILLAS CÓMODAS Y ESTILIZADAS CON LAS 3 TIRAS CONTRASTANTES",
        description: "Estas zapatillas adidas actualizan un diseño clásico con una llamativa combinación de colores. Su diseño le da un toque de estilo a tus looks informales o tus veladas con amigos. La parte superior suave trae un forro interno que envuelve el pie en comodidad y la suela de caucho flexible y ligera te proporciona un excelente agarre.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027950/Proyecto-Reacts/Zapatillas/q0q8flzgjekxlzbocmwa.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027950/Proyecto-Reacts/Zapatillas/v6lombfihzwb1aa9z8td.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027951/Proyecto-Reacts/Zapatillas/t2oqtcgsfdqz88yay3l2.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027954/Proyecto-Reacts/Zapatillas/qkzibqho4phfd8z7rjzg.webp",
    },
    {
        id: "4",
        marca:"Adidas",
        title: "Zapatillas adidas Midcity Low",
        price: 159.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "TENIS DE INSPIRACIÓN RETRO HECHOS EN PARTE CON MATERIALES RECICLADOS",
        description: "Estos tenis adidas se inspiran en la estética de finales de los 80 con un look estilizado y una sensación de comodidad inmediata. El exterior presenta una mezcla de piel sintética y tela para lograr un look auténtico. La mediasuela con amortiguación Cloudfoam te ofrece una pisada más cómoda para todo lo que te depare el día. El exterior contiene al menos un 50 % de materiales reciclados. Este producto representa solo una de las soluciones de adidas para ayudar a poner fin a los residuos plásticos",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027969/Proyecto-Reacts/Zapatillas/ogoa8s6ljw0zfkttvp7u.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027972/Proyecto-Reacts/Zapatillas/bjdk2lkmfxwdbgcwfkqg.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027970/Proyecto-Reacts/Zapatillas/dazcz1tkkcorxtpis92y.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027971/Proyecto-Reacts/Zapatillas/joq1jzpszignhapuknpi.webp",
    },
    {
        id: "5",
        marca: "Adidas",
        title: "Zapatillas adidas Forum Mid",
        price: 129.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "ZAPATILLAS DE CORTE MEDIO HECHAS PARCIALMENTE CON MATERIALES RECICLADOS",
        description: "Estas zapatillas adidas Forum Mid le imprimen modernidad a una versión clásica. El cuero prémium y la gamuza se unen en una mezcla de texturas y tonos para crear un look de inspiración vintage perfecto para el presente. Con una tira ajustable de cierre por contacto y una suela tipo cupsole de caucho, estas zapatillas son tan cómodas como un paseo de domingo y tan elegantes como una salida nocturna. Mantienen tus pies con estilo y comodidad de la mañana a la noche.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027966/Proyecto-Reacts/Zapatillas/wrqtk4mxzfkz1yprbgko.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027966/Proyecto-Reacts/Zapatillas/p41lqdhlhrxho1hlyeh3.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027967/Proyecto-Reacts/Zapatillas/qskbihxicgrvj2acylf5.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027967/Proyecto-Reacts/Zapatillas/vlaok3pexqo2deye52dh.webp",
    },
    {
        id: "6",
        marca: "Nike",
        title: "Zapatillas Nike Air Force 1 ",
        price: 229.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "TENIS DE INSPIRACIÓN UNICA",
        description: "El resplandor sigue vivo en el AF1 '07, que brinda un estilo atemporal fácil de usar. El cuero duradero brinda a este calzado un aire clásico, al mismo tiempo que los paneles laterales perforados en Rojo Universitario agregan la cantidad justa de estilo para que brilles. Por supuesto, algunas cosas nunca cambian: las unidades Nike Air mantienen amortiguación en cada pisada.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027957/Proyecto-Reacts/Zapatillas/kqlsufu4pv2blhvp6km6.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027958/Proyecto-Reacts/Zapatillas/ubkw1iclsvd6vkcmymej.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027962/Proyecto-Reacts/Zapatillas/rto7mjv2xaf3t8bknjbv.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027958/Proyecto-Reacts/Zapatillas/lkkcakridbycrsookogd.webp",
        
    },
    {
        id: "7",
        marca: "Nike",
        title: "Zapatillas Nike Dunk Low Retro",
        price: 229.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "Estilo Vintage con Comodidad Moderna",
        description: "Inspiradas en las canchas de basket de los años 80, estas zapatillas combinan un diseño icónico con materiales de alta calidad y detalles funcionales.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027960/Proyecto-Reacts/Zapatillas/n7vtgnpus71qivshdd6y.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027950/Proyecto-Reacts/Zapatillas/a8yeso1npzqcnyrp1bhd.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027947/Proyecto-Reacts/Zapatillas/hlw4hfo40o1acmbchkr6.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027955/Proyecto-Reacts/Zapatillas/di2iipyzg3yl4k9aednm.webp",
    },
    {
        id: "8",
        marca: "Nike",
        title: "Zapatillas Nike TC 7900",
        price: 239.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "Resistente y sólido",
        description: "Diseñada para durar, la parte superior cuenta con capas de materiales sintéticos que optimizan la durabilidad. Los detalles en red y de goma en el talón aportan lo suyo a un look que derrocha solidez. La gruesa amortiguación de espuma agrega una comodidad increíble mientras que los detalles de goma en la suela aportan durabilidad y tracción.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027956/Proyecto-Reacts/Zapatillas/r1fw77opkad5areb9kb6.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027957/Proyecto-Reacts/Zapatillas/g2025uq9k4lmccraep9s.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027958/Proyecto-Reacts/Zapatillas/e1vwyvkpzwl4cxd51f4p.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027956/Proyecto-Reacts/Zapatillas/pfpskvl9zxnspeckd4ew.webp",
    },
    {
        id: "9",
        marca: "Nike",
        title: "Zapatillas Nike Air Max 90",
        price: 259.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "Nike Air Max 90",
        description: "El ícono de los 90 regresa con estilo retro y máxima comodidad para tu día a día.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027959/Proyecto-Reacts/Zapatillas/ilolpnhzcg3d9ov08741.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027959/Proyecto-Reacts/Zapatillas/oaqxhkkzb9eroyrudjdc.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027960/Proyecto-Reacts/Zapatillas/gfprztn4wxnb4btbalzp.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027961/Proyecto-Reacts/Zapatillas/qnterrtlo5yi7zi8a3pp.webp",
    },
    {
        id: "10",
        marca: "Nike",
        title: "Zapatillas Nike Air Force 1 Low Retro",
        price: 309.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "Las Air Force Mas Famosas",
        description: "Esta versión, que rinde homenaje a mediados de los 80, cuando las tiendas de zapatillas de Baltimore volvieron a poner de moda las Air Force 1 con una serie de combinaciones de colores personalizadas.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027951/Proyecto-Reacts/Zapatillas/ztfrtiy5bqdl37ah9uoy.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027951/Proyecto-Reacts/Zapatillas/ci4avpebnq1y0ljr9auv.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027953/Proyecto-Reacts/Zapatillas/v3zyh1fjukb4rmzio1kd.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027954/Proyecto-Reacts/Zapatillas/jzuqi4lakap69kaacqpq.webp",
    },
    {
        id: "11",
        marca: "Fila",
        title: "Zapatillas Fila Uproot",
        price: 149.899,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "ULTRACOMODAS Y UN ESTILO UNICO",
        description: "Las zapatillas Fila UPROOT son otro modelo de la línea HERITAGE con un toque de los 90´s y con suela de caucho que brinda confort al caminar, uno de los diseños Ugly Shoes para los estilos más casuales hasta los más vanguardistas, para usar todos los días y en todo momento.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027954/Proyecto-Reacts/Zapatillas/dczekmywqwjuh75r8fij.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027954/Proyecto-Reacts/Zapatillas/tjvrsoht1q2duubkanwt.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027957/Proyecto-Reacts/Zapatillas/ojq8wz8xmmewvjtdnghf.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027955/Proyecto-Reacts/Zapatillas/dj6sega8rtsrfkfsjigs.webp",
    },
    {
        id: "12",
        marca: "Reebok",
        title: "Zapatillas Reebok Royal",
        price: 99.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "COMODAS Y UN DISEÑO MODERNO",
        description: "Los años 90 fueron el hogar de algunos de los uniformes de baloncesto más llamativos, llenos de combinaciones de colores atrevidas y audaces. Estas zapatillas Reebok hacen un viaje al pasado y toman algunas referencias de las Pump Omni para darles un aspecto retro. Los detalles sintéticos en toda la parte superior aportan ese estilo de la vieja escuela y una sensación estructurada.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027961/Proyecto-Reacts/Zapatillas/k2x04tljibik35efklgj.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027963/Proyecto-Reacts/Zapatillas/kpwxhbgi1vy3rxwigbtk.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027962/Proyecto-Reacts/Zapatillas/uchjdhlrsigppl9ougxc.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027962/Proyecto-Reacts/Zapatillas/yyed8uza3xudujs7f8td.webp",
    },
    {
        id: "13",
        marca: "Reebok",
        title: "Zapatillas Reebok Classic Leather",
        price: 79.999,
        stock: 15,
        Genero: "Hombre",
        descriptionTitle: "Zapatillas Reebok Classic Leather",
        description: "Siempre formarás parte del equipo cuando lleves estos zapatos Reebok Classic Leather. Los colores universitarios y las franjas laterales de dos tonos mejoran tu juego de entrenamiento.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027958/Proyecto-Reacts/Zapatillas/ovbedpvcab048qqtcm0n.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027959/Proyecto-Reacts/Zapatillas/qctqiwkh5bziqqzycu97.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027963/Proyecto-Reacts/Zapatillas/dlzatmhqe1dgh8oz7yz1.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027959/Proyecto-Reacts/Zapatillas/x0xhyowq5zdriykzoup3.webp",
    },
    {
        id: "14",
        marca: "Vans",
        title: "Zapatillas Vans U SK8-HI",
        price: 138.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "LIGERAS, CLASICAS Y COMODAS",
        description: "Las Sk8-Hi de Vans son unas zapatillas ligeras, de caña alta y con cordones. Presenta amortiguación en el talón para más confort, una puntera reforzada que garantiza la durabilidad y cuello acolchado para mayor sujeción y flexibilidad. Está hecha con una parte superior de lona y gamuza resistente. La distintiva suela waffle de caucho proporciona un agarre más firme.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027965/Proyecto-Reacts/Zapatillas/weatiyaghiz4j1f5m8js.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027965/Proyecto-Reacts/Zapatillas/l0gyr922doleuyrffmpj.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027965/Proyecto-Reacts/Zapatillas/lej2uvzdxf13z6ka4t9l.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027966/Proyecto-Reacts/Zapatillas/jm6ajnfoerrlq7c2qkvk.webp",
    },
    {
        id: "15",
        marca: "Vans",
        title: "Zapatillas Vans Filmore Hi",
        price: 145.999,
        stock: 15,
        Genero: "Mujer",
        descriptionTitle: "Vans Filmore Hi",
        description: "Las zapatillas Vans Filmore Hi poseen un estilo icónico diseñado específicamente para la práctica del skate, Plantillas que se ajustan perfectamente y no se apelmazan, lo que proporciona una óptima protección contra impactos y un retorno de energía personalizado sea cual sea tu estilo al patinar.",
        imageUrl: "https://res.cloudinary.com/djcguwdgr/image/upload/v1739027963/Proyecto-Reacts/Zapatillas/c8y8ymro0bwp4puuwiyz.webp",
        img1:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027963/Proyecto-Reacts/Zapatillas/wgart1ygwfigs6xjb7yh.webp",
        img2:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027963/Proyecto-Reacts/Zapatillas/dnkzg1vspmvmxqxt5vca.webp",
        img3:"https://res.cloudinary.com/djcguwdgr/image/upload/v1739027972/Proyecto-Reacts/Zapatillas/lrrtihu1ru6zbydtaslh.webp",
    },

];