export const products = [
    {
        id: "1",
        title: "Adidas",
        price: 250,
        stock: 15,
        category: "Urbano",
        description: "las mejores",
        imageUrl: "",
    },
    {
        id: "2",
        title: "Nike",
        price: 230,
        stock: 9,
        category: "deportivas",
        description: "las mejores",
        imageUrl: "",
    },
    {
        id: "3",
        title: "Puma",
        price: 200,
        stock: 10,
        category: "deportivas",
        description: "las mejores",
        imageUrl: "",
    },
    {
        id: "4",
        title: "Topper",
        price: 190,
        stock: 6,
        category: "Trabajo",
        description: "las mejores",
        imageUrl: "",
    },
    {
        id: "5",
        title: "Fila",
        price: 200,
        stock: 8,
        category: "Urbano",
        description: "las mejores",
        imageUrl: "",
    },
    {
        id: "6",
        title: "Salomon",
        price: 200,
        stock: 5,
        category: "Trabajo",
        description: "las mejores",
        imageUrl: "",
    },
];